### ISSUE TITLE
Bug: Cache evicts newest entries instead of oldest?

### ISSUE THREAD

**Issue by PragTob** [hissssst/nebulex_adapters_ecto#4]
Hi there,

thanks for the project!

Me again, I haven't tested it yet so there's a chance I'm wrong but from reviewing the code I think the code where the GC deletes entries is deleting the newest entries, not the oldest:

```elixir
    # Remove oldest and exceeding entries
    repo.delete_all(
      from(x in table,
        where:
          ctid() in subquery(
            from(x in table, select: ctid(), order_by: x.touched_at, offset: ^max_amount)
          )
      )
    )
```

* order_by defaults to "ascending" so we'll order them from oldest to youngest (as old time stamps are lower than young ones)
* offset comes in and skips `max_amount` rows, which in our case will be the oldest so the remaining rows (if any) are the youngest rows
* we then delete the most recently used rows, which is not what LRU or LRW want to the best of my understanding and not what the comment suggests

Fix should be easy, a descending order_by should be fine but would also accompany it with tests.

**Comment by hissssst** [comment]
Thanks, good catch
